from django.urls import path

from .views import (
    RegistrationView,
    LoginView,
    LogoutView,
    PasswordResetConfirmView,
    IndexView,
    RegisterPersonel,
    CommunicationView,
    GetLastRecognized,
    PasswordChangeView,
    EditPersonalView,
    DeletePersonalView,
    PersonalEnterLogView,
    PersonalExitLogView,
    PersonalLogReportView,
    DownloadPersonalLogView,
    OperatorLogReportView,
    DownloadOperatorLogView,
    EditOperatorView,
    DeleteOperatorView,
    DoorComView,
    TotalComView,
    GetAlarmView,
    livestream_view,
    DeleteFaceView,
    DeleteFingerView,
)

app_name = 'accounts'

urlpatterns = [
    path("signup/", RegistrationView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("index/", IndexView.as_view(), name="index"),
    path("reg-personel/", RegisterPersonel.as_view(), name="reg-personel"),
    path("communication/<action>/", CommunicationView.as_view(), name="communication-action",),
    path("get-last-person/", GetLastRecognized.as_view(), name="get-last-person",),
    path("password-change/", PasswordChangeView.as_view(), name="password-change",),
    path("edit-personel/", EditPersonalView.as_view(), name="edit-personal",),
    path("delete-personel/", DeletePersonalView.as_view(), name="delete-personal",),
    path("personellog-enter-request/", PersonalEnterLogView.as_view(), name="personellog-enter-request",),
    path("personellog-exit-request/", PersonalExitLogView.as_view(), name="personellog-exit-request",),
    path("personellog-report/", PersonalLogReportView.as_view(), name="personellog-report",),
    path("download-report/", DownloadPersonalLogView.as_view(), name="download-report",),
    path("operator-log-report/", OperatorLogReportView.as_view(), name="operator-log-report",),
    path("download-operator-report/", DownloadOperatorLogView.as_view(), name="download-operator-report",),
    path("edit-operator/", EditOperatorView.as_view(), name="edit-operator",),
    path("delete-operator/", DeleteOperatorView.as_view(), name='delete-operator'),
    path("door-com/", DoorComView.as_view(), name='door-com'),
    path("total-com/", TotalComView.as_view(), name='total-com'),
    path("get-alarm/", GetAlarmView.as_view(), name="get-alarm"),
    path("reg-camera/", livestream_view, name="reg-camera"),
    path("delete-face/", DeleteFaceView.as_view(), name="delete-face"),
    path("delete-finger/", DeleteFingerView.as_view(), name="delete-finger"),

]
