# Generated by Django 5.0.1 on 2024-10-20 09:51

import django.contrib.auth.validators
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_door', models.BooleanField(default=1, max_length=1)),
                ('delete_req', models.BooleanField(default=0, max_length=1)),
                ('restart', models.BooleanField(default=0, max_length=1)),
                ('alarm1', models.BooleanField(default=0, max_length=1)),
                ('alarm2', models.BooleanField(default=0, max_length=1)),
            ],
            options={
                'db_table': 'communication',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('check_req', models.BooleanField(default=0, max_length=1)),
                ('check_ok', models.BooleanField(default=0, max_length=1)),
                ('check_nok', models.BooleanField(default=0, max_length=1)),
                ('access_control', models.BooleanField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('NID', models.CharField(max_length=10)),
                ('PID', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('job', models.CharField(max_length=50)),
                ('expire', django_jalali.db.models.jDateField()),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.department')),
            ],
            options={
                'db_table': 'operator_reg',
            },
        ),
        migrations.CreateModel(
            name='DoorOpenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', django_jalali.db.models.jDateTimeField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', django_jalali.db.models.jDateField()),
                ('time_in', models.TimeField()),
                ('date_out', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('exit', 'Exit'), ('entry', 'Entry')], max_length=20)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operator_log',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('PID', models.CharField(max_length=20, unique=True)),
                ('shift', models.JSONField(max_length=150)),
                ('position', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('permit', models.JSONField(max_length=200)),
                ('permit_date_start', django_jalali.db.models.jDateField()),
                ('permit_date_stop', django_jalali.db.models.jDateField()),
                ('permit_time_start', models.TimeField()),
                ('permit_time_stop', models.TimeField()),
                ('phone', models.CharField(max_length=11)),
                ('parent_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('certify', models.BooleanField(default=0, max_length=1)),
                ('date_joined', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.department')),
                ('first_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persoanl_first_editor', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('second_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persoanl_second_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_reg',
            },
        ),
        migrations.CreateModel(
            name='PersonalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', django_jalali.db.models.jDateField(default='1400-01-01')),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('date_out', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('exit', 'Exit'), ('entry', 'Entry')], max_length=20)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.personal')),
            ],
            options={
                'db_table': 'personal_log',
            },
        ),
    ]
