# Generated by Django 5.0.1 on 2024-10-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='disablelogin',
            field=models.BooleanField(default=0, max_length=1),
        ),
    ]
